<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NoResultException;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository {

    public function findClientByPushSubscriptionPublicKey($publicKey) {
        $query = $this->createQueryBuilder('c')
            ->select('c')
            ->leftJoin('c.pushSubscriptionSettings', 's')
            ->where('s.publicKey = :param')
            ->setParameter('param', $publicKey)
            ->getQuery();

        try {
            $result = $query->getSingleResult();
        } catch (NoResultException $ex) {
            $result = null;
        }
        return $result;

    }


}
