<?php

namespace AppBundle\Repository;

/**
 * PushMessageHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushMessageHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
