<?php

namespace AppBundle\Repository;

/**
 * PushSubscriptionSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushSubscriptionSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
