<?php

namespace AppBundle\Repository;

/**
 * PushSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushSubscriptionRepository extends \Doctrine\ORM\EntityRepository {

    public function persistSubscriptionIfNotExists($subscription) {
        $exists = $this->findOneBy(['endpoint' => $subscription->getEndpoint()]);
        if (!$exists) {
            $this->getEntityManager()->persist($subscription);
            $this->getEntityManager()->flush();
        }
    }

}
