<?php

namespace AppBundle\Repository;

/**
 * PushNotificationScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushNotificationScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
