<?php

namespace AppBundle\Repository;

/**
 * PushMessageScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushMessageScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
