<?php

namespace AppBundle\Command;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Filesystem\Filesystem;


/**
 * @author mathil <github.com/mathil>
 */
class ClearTempDirCommand extends ContainerAwareCommand
{

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('bm:clear:temp-dir');
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $tempDir = $this->getContainer()->getParameter('temp_files_dir');

        if (false === file_exists($tempDir)) {
            $output->writeln(sprintf('Directory %dir does not exists.', $tempDir));
            return;
        }

        $files = scandir($tempDir);
        foreach ($files as $file) {
            if (in_array($file, ['.', '..'])) {
                continue;
            }
            unlink($tempDir . $file);
        }
        $output->writeln(sprintf('%d files deleted.', count($files) - 2));
    }

}